### ISSUE TITLE
Agent olarak çalışma

### ISSUE THREAD

**Issue by molgun** [KarBoraN/SelecTra#2]
Bunun agent olarak çalışması lazım nasıl yapacaksın bilmiyorum ama. Yani sürekli arkada çalışacak bir kelime selected olduğu zaman bir Event'in çalışması lazım sürekli olsun yoksa bu haliyle çok kullanışsız var mı bir fikrin bu konuda

**Comment by ysfduzgun** [comment]
Nasıl yani ben kelime seçince arkadan oto çalışıp arama yapsın ?.

**Comment by molgun** [comment]
Aynen kesin kullandığın kütüphanenin böyle bir event sağlaması lazım. onSelected diye mesela.

**Comment by ysfduzgun** [comment]
Programı zaten elle python ... selected.py diye çalıştırmıyoruzki. Sistemin klavye kısayollarına ekleyerek kullanıyoruz :) .
Resimdeki gibi.
![örnek](http://i.hizliresim.com/oZBADm.png)

Ama calistirabilir dosya haline getirip ../bin altında birşeyler ayarlayabiliriz onun için biraz uğraşayım.
